[[piglit]]
piglit_folder = "/piglit"
profile = "quick_gl"
process_isolation = true
  [piglit.env]
  PIGLIT_PLATFORM = "mixed_glx_egl"

[[piglit]]
piglit_folder = "/piglit"
profile = "quick_shader"
fraction = 2
process_isolation = true
  [piglit.env]
  PIGLIT_PLATFORM = "mixed_glx_egl"
